version: "3.8"

networks:
  default:
    external:
      name: dcd

services:
  db:
    container_name: dcd-db
    image: mariadb:latest
    env_file: dcd-db.env
    ports:
      - 3307:3306
  redis:
    container_name: dcd-redis
    image: redis:latest
    env_file: dcd-redis.env
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6378:6379
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
  proxy:
    container_name: dcd-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
