version: "3.8"

networks:
  default:
    external:
      name: dcd

services:
  db:
    platform: linux/arm/v7
    container_name: dcd-db
    image: linuxserver/mariadb:arm32v7-latest
    env_file: dcd-db.env
    ports:
      - 3307:3306
  redis:
    platform: linux/arm/v7
    container_name: dcd-redis
    image: redis:7.4.1-alpine
    env_file: dcd-redis.env
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6378:6379
    command: ["redis-server", "--requirepass", "$$REDIS_PASSWORD"]
