spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSecret: ${JWT_REFRESH_SECRET}
  time:
    accessTime: ${JWT_ACCESS_TIME}
    refreshTime: ${JWT_REFRESH_TIME}
server:
  port: 8080