name: Build and Test
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6378:6379
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        enableCrossOsArchive: true

    - name: create test env file
      run: |
        cat << EOF > test.env
        ${{secrets.TEST_ENV}}
        EOF

    - name: apply test env
      run: |
        set -a
        source test.env
        set +a
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build -Dspring.profiles.active=test
